/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : TZ
 #	author : miyako
 #	2018/06/24
 #
 # --------------------------------------------------------------------------------*/

#include "date/tz.h"
#include "libjson.h"
#include "libjson_methods.h"
#include <iostream>

// --- TZ
void TZ_Convert(sLONG_PTR *pResult, PackagePtr pParams);
void TZ_Get_zones(sLONG_PTR *pResult, PackagePtr pParams);
